'use client'

import { useEffect, useState, useRef } from 'react'
import { supabase } from '@/lib/supabase'
import { User, Move, SponsoredChallenge, DREAM_CATEGORIES, PACE_OPTIONS } from '@/lib/types'
import { Download, Copy, Check, Flower2, TrendingUp, Users, Target, Crown } from 'lucide-react'
import { format, subDays, differenceInDays, parseISO } from 'date-fns'

export default function ReportsPage() {
  const [users, setUsers] = useState<User[]>([])
  const [moves, setMoves] = useState<Move[]>([])
  const [challenges, setChallenges] = useState<SponsoredChallenge[]>([])
  const [loading, setLoading] = useState(true)
  const [copied, setCopied] = useState(false)
  const reportRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    fetchData()
  }, [])

  async function fetchData() {
    try {
      const [usersRes, movesRes, challengesRes] = await Promise.all([
        supabase.from('users').select('*'),
        supabase.from('moves').select('*'),
        supabase.from('sponsored_challenges').select('*'),
      ])

      if (usersRes.data) setUsers(usersRes.data)
      if (movesRes.data) setMoves(movesRes.data)
      if (challengesRes.data) setChallenges(challengesRes.data)
    } catch (error) {
      console.error('Error fetching data:', error)
    } finally {
      setLoading(false)
    }
  }

  // Calculate metrics
  const today = new Date()
  const last7DaysUsers = users.filter(u =>
    differenceInDays(today, parseISO(u.created_at)) <= 7
  ).length

  const last30DaysUsers = users.filter(u =>
    differenceInDays(today, parseISO(u.created_at)) <= 30
  ).length

  const growthRate = users.length > last30DaysUsers
    ? Math.round((last30DaysUsers / (users.length - last30DaysUsers)) * 100)
    : 100

  // DAU calculation
  const todayStr = format(today, 'yyyy-MM-dd')
  const dau = new Set(
    moves.filter(m => m.completed_at.split('T')[0] === todayStr).map(m => m.user_id)
  ).size

  // MAU calculation
  const mau = new Set(
    moves.filter(m => differenceInDays(today, parseISO(m.completed_at)) <= 30).map(m => m.user_id)
  ).size

  const dauMauRatio = mau > 0 ? Math.round((dau / mau) * 100) : 0

  // Average moves per day
  const uniqueDays = new Set(moves.map(m => m.completed_at.split('T')[0])).size
  const avgMovesPerDay = uniqueDays > 0 ? Math.round(moves.length / uniqueDays) : 0

  // Category breakdown
  const categoryBreakdown = DREAM_CATEGORIES.map(cat => ({
    ...cat,
    count: users.filter(u => u.dream_category === cat.value).length,
    percentage: users.length > 0
      ? Math.round((users.filter(u => u.dream_category === cat.value).length / users.length) * 100)
      : 0,
  }))

  // Pace breakdown
  const paceBreakdown = PACE_OPTIONS.map(pace => ({
    ...pace,
    count: users.filter(u => u.pace === pace.value).length,
    percentage: users.length > 0
      ? Math.round((users.filter(u => u.pace === pace.value).length / users.length) * 100)
      : 0,
  }))

  // Premium rate
  const premiumCount = users.filter(u => u.is_premium).length
  const premiumRate = users.length > 0 ? Math.round((premiumCount / users.length) * 100) : 0

  // Active challenges stats
  const activeChallenges = challenges.filter(c => c.is_active)

  function copyStats() {
    const stats = `
DELUSIONAL LEAP - BRAND REPORT
Generated: ${format(today, 'MMMM d, yyyy')}

📊 USER METRICS
• Total Users: ${users.length.toLocaleString()}
• New Users (7 days): ${last7DaysUsers}
• New Users (30 days): ${last30DaysUsers}
• Growth Rate: ${growthRate}%

📈 ENGAGEMENT
• Daily Active Users: ${dau}
• Monthly Active Users: ${mau}
• DAU/MAU Ratio: ${dauMauRatio}%
• Avg Moves/Day: ${avgMovesPerDay}
• Total Moves: ${moves.length.toLocaleString()}

💫 DREAM CATEGORIES
${categoryBreakdown.map(c => `• ${c.emoji} ${c.label}: ${c.percentage}%`).join('\n')}

⚡ PACE PREFERENCES
${paceBreakdown.map(p => `• ${p.emoji} ${p.label}: ${p.percentage}%`).join('\n')}

👑 PREMIUM
• Premium Users: ${premiumCount}
• Conversion Rate: ${premiumRate}%

🏆 SPONSORED CHALLENGES
• Active Challenges: ${activeChallenges.length}
• Total Challenges: ${challenges.length}

---
Generated by Delusional Leap Dashboard
    `.trim()

    navigator.clipboard.writeText(stats)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  async function exportPDF() {
    // For a real implementation, you'd use a library like html2pdf or jspdf
    // For now, we'll use the browser's print functionality
    window.print()
  }

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="text-gray-500">Loading report data...</div>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-semibold text-gray-900">Brand Reports</h1>
          <p className="text-gray-500 mt-1">
            Generate and share stats with brands and sponsors
          </p>
        </div>
        <div className="flex items-center gap-3">
          <button onClick={copyStats} className="btn btn-outline">
            {copied ? (
              <>
                <Check className="w-4 h-4 text-green-600" />
                Copied!
              </>
            ) : (
              <>
                <Copy className="w-4 h-4" />
                Copy Stats
              </>
            )}
          </button>
          <button onClick={exportPDF} className="btn btn-primary">
            <Download className="w-4 h-4" />
            Export as PDF
          </button>
        </div>
      </div>

      {/* Report Content */}
      <div ref={reportRef} className="space-y-6 print:space-y-4">
        {/* Report Header */}
        <div className="card">
          <div className="p-8 bg-gradient-to-r from-[#FF3366] to-[#FF6B35] rounded-t-lg text-white">
            <div className="flex items-center gap-3 mb-4">
              <Flower2 className="w-10 h-10" />
              <div>
                <h2 className="text-2xl font-bold">Delusional Leap</h2>
                <p className="opacity-90">Brand Partnership Report</p>
              </div>
            </div>
            <p className="text-lg opacity-90">
              Generated on {format(today, 'MMMM d, yyyy')}
            </p>
          </div>
          <div className="p-6">
            <p className="text-gray-600">
              Delusional Leap is a gamified goal-achievement app that helps users chase their
              dreams through daily micro-actions called &quot;moves.&quot; Our engaged community is
              actively working towards meaningful life goals across travel, career, side hustles,
              and personal growth.
            </p>
          </div>
        </div>

        {/* Key Stats Grid */}
        <div className="grid grid-cols-4 gap-4">
          <div className="card p-6 text-center">
            <Users className="w-8 h-8 text-[#FF3366] mx-auto mb-2" />
            <div className="text-3xl font-bold text-gray-900">{users.length.toLocaleString()}</div>
            <div className="text-sm text-gray-500">Total Users</div>
            <div className="text-xs text-green-600 mt-1">+{last7DaysUsers} this week</div>
          </div>
          <div className="card p-6 text-center">
            <Target className="w-8 h-8 text-[#FBBF24] mx-auto mb-2" />
            <div className="text-3xl font-bold text-gray-900">{moves.length.toLocaleString()}</div>
            <div className="text-sm text-gray-500">Total Moves</div>
            <div className="text-xs text-gray-400 mt-1">{avgMovesPerDay}/day avg</div>
          </div>
          <div className="card p-6 text-center">
            <TrendingUp className="w-8 h-8 text-[#4ADE80] mx-auto mb-2" />
            <div className="text-3xl font-bold text-gray-900">{dauMauRatio}%</div>
            <div className="text-sm text-gray-500">DAU/MAU Ratio</div>
            <div className="text-xs text-gray-400 mt-1">Strong engagement</div>
          </div>
          <div className="card p-6 text-center">
            <Crown className="w-8 h-8 text-[#FF6B35] mx-auto mb-2" />
            <div className="text-3xl font-bold text-gray-900">{premiumRate}%</div>
            <div className="text-sm text-gray-500">Premium Rate</div>
            <div className="text-xs text-gray-400 mt-1">{premiumCount} subscribers</div>
          </div>
        </div>

        {/* Audience Demographics */}
        <div className="grid grid-cols-2 gap-6">
          {/* Dream Categories */}
          <div className="card">
            <div className="card-header">
              <h3 className="font-medium text-gray-900">Audience by Dream Category</h3>
            </div>
            <div className="card-body space-y-4">
              {categoryBreakdown.map(cat => (
                <div key={cat.value}>
                  <div className="flex items-center justify-between mb-1">
                    <span className="text-sm text-gray-600">
                      {cat.emoji} {cat.label}
                    </span>
                    <span className="text-sm font-medium">{cat.percentage}%</span>
                  </div>
                  <div className="h-2 bg-gray-100 rounded-full overflow-hidden">
                    <div
                      className="h-full bg-gradient-to-r from-[#FF3366] to-[#FF6B35] rounded-full"
                      style={{ width: `${cat.percentage}%` }}
                    />
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Pace Preferences */}
          <div className="card">
            <div className="card-header">
              <h3 className="font-medium text-gray-900">User Pace Preferences</h3>
            </div>
            <div className="card-body space-y-4">
              {paceBreakdown.map(pace => (
                <div key={pace.value}>
                  <div className="flex items-center justify-between mb-1">
                    <span className="text-sm text-gray-600">
                      {pace.emoji} {pace.label}
                    </span>
                    <span className="text-sm font-medium">{pace.percentage}%</span>
                  </div>
                  <div className="h-2 bg-gray-100 rounded-full overflow-hidden">
                    <div
                      className="h-full bg-[#FBBF24] rounded-full"
                      style={{ width: `${pace.percentage}%` }}
                    />
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Engagement Metrics */}
        <div className="card">
          <div className="card-header">
            <h3 className="font-medium text-gray-900">Engagement Metrics</h3>
          </div>
          <div className="card-body">
            <table className="notion-table">
              <thead>
                <tr>
                  <th>Metric</th>
                  <th>Value</th>
                  <th>Industry Benchmark</th>
                  <th>Status</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>Daily Active Users (DAU)</td>
                  <td className="font-medium">{dau}</td>
                  <td className="text-gray-500">—</td>
                  <td>
                    <span className="badge badge-green">Active</span>
                  </td>
                </tr>
                <tr>
                  <td>Monthly Active Users (MAU)</td>
                  <td className="font-medium">{mau}</td>
                  <td className="text-gray-500">—</td>
                  <td>
                    <span className="badge badge-green">Healthy</span>
                  </td>
                </tr>
                <tr>
                  <td>DAU/MAU Ratio</td>
                  <td className="font-medium">{dauMauRatio}%</td>
                  <td className="text-gray-500">10-20%</td>
                  <td>
                    <span className={`badge ${dauMauRatio >= 20 ? 'badge-green' : 'badge-yellow'}`}>
                      {dauMauRatio >= 20 ? 'Excellent' : 'Good'}
                    </span>
                  </td>
                </tr>
                <tr>
                  <td>Average Moves per Day</td>
                  <td className="font-medium">{avgMovesPerDay}</td>
                  <td className="text-gray-500">—</td>
                  <td>
                    <span className="badge badge-green">Engaged</span>
                  </td>
                </tr>
                <tr>
                  <td>Premium Conversion</td>
                  <td className="font-medium">{premiumRate}%</td>
                  <td className="text-gray-500">2-5%</td>
                  <td>
                    <span className={`badge ${premiumRate >= 5 ? 'badge-green' : 'badge-yellow'}`}>
                      {premiumRate >= 5 ? 'Above Avg' : 'On Track'}
                    </span>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>

        {/* Sponsored Challenges Performance */}
        {challenges.length > 0 && (
          <div className="card">
            <div className="card-header">
              <h3 className="font-medium text-gray-900">Sponsored Challenges</h3>
            </div>
            <div className="card-body">
              <table className="notion-table">
                <thead>
                  <tr>
                    <th>Challenge</th>
                    <th>Sponsor</th>
                    <th>Status</th>
                    <th>Dates</th>
                  </tr>
                </thead>
                <tbody>
                  {challenges.slice(0, 5).map(challenge => (
                    <tr key={challenge.id}>
                      <td className="font-medium">{challenge.title}</td>
                      <td className="text-gray-600">{challenge.sponsor_name || '—'}</td>
                      <td>
                        <span className={`badge ${challenge.is_active ? 'badge-green' : 'badge-gray'}`}>
                          {challenge.is_active ? 'Active' : 'Ended'}
                        </span>
                      </td>
                      <td className="text-gray-500 text-sm">
                        {challenge.start_date && challenge.end_date ? (
                          <>
                            {format(parseISO(challenge.start_date), 'MMM d')} -{' '}
                            {format(parseISO(challenge.end_date), 'MMM d')}
                          </>
                        ) : (
                          'No dates'
                        )}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )}

        {/* Footer */}
        <div className="card p-6 text-center print:mt-8">
          <div className="flex items-center justify-center gap-2 text-gray-400 mb-2">
            <Flower2 className="w-5 h-5" />
            <span className="font-medium">Delusional Leap</span>
          </div>
          <p className="text-sm text-gray-500">
            Contact: gabby@delusionalleap.com | www.delusionalleap.com
          </p>
        </div>
      </div>
    </div>
  )
}
